-- This module is the root of the BorelConjectureCanonicalLaneLean Lean proof package.
import BorelConjectureCanonicalLaneLean.Basic
import BorelConjectureCanonicalLaneLean.SourcePackage
import BorelConjectureCanonicalLaneLean.SourceDependencies
import BorelConjectureCanonicalLaneLean.Formalization
import BorelConjectureCanonicalLaneLean.ReviewerBridge
import BorelConjectureCanonicalLaneLean.TheoremStatement
import BorelConjectureCanonicalLaneLean.MathlibObjects
import BorelConjectureCanonicalLaneLean.AdmissibleClass
import BorelConjectureCanonicalLaneLean.Projection
import BorelConjectureCanonicalLaneLean.BridgeLemmas
import BorelConjectureCanonicalLaneLean.GateLemmas
import BorelConjectureCanonicalLaneLean.FinalTheorem
import BorelConjectureCanonicalLaneLean.MathlibStatement
